services:
  mysql_test:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - database-volume-test:/var/lib/mysql

  php_test:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/symfony/:/usr/src/app'
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./apps/symfony/var/coverage:/opt/phpstorm-coverage
    restart: on-failure
    user: ${LOCAL_USER}
    environment:
      DATABASE_URL: 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql_test:3306/${MYSQL_DATABASE}?serverVersion=8.0.24'
      MAILER_DSN: 'null://null'
    depends_on:
      - mysql_test
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  database-volume-test:
    driver: local
